### ISSUE TITLE
Tile Not Available - Direct access?

### ISSUE THREAD

**Issue by machadoug** [komoot/staticmap#11]
Greetings,

I'm looking for ways to integrate this sscript with PHP. I've tried to access the image directly, but it doesn't work.
When I enter the URL in the browser I get 
> Tile Not Available

http://a.tile.komoot.de/komoot-2/15/40.730610/-73.935242.png

**Comment by christophlingg** [comment]
you can't pass coordinates to access map tiles, have a look here http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames
