### ISSUE TITLE
Update breaks my production environment

### ISSUE THREAD

**Issue by raratiru** [komoot/staticmap#13]
While upgrading the python environment in my production server, I encountered the following fatal error:

```
  Downloading staticmap-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in staticmap setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in futures;python_version<"3.2" at ;python_version<"3.2"
```

```
$ pip --version
pip 9.0.1 from ~/.virtualenvs/<>/lib/python3.5/site-packages (python 3.5)

```
In my home server, I only receive the following warning:

`Ignoring futures: markers 'python_version < "3.2"' don't match your environment`

```
$ pip --version
pip 9.0.1 from ~/.virtualenvs/<>/lib/python3.4/site-packages (python 3.4)
```

**Comment by christophlingg** [comment]
the declaration seems to be correct and follows [the documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies). I can't really tell you why it fails on your production system. [Here](https://github.com/fugue/credstash/issues/124) they were suggesting to try

> pip install -U setuptools

**Comment by raratiru** [comment]
Indeed that did the trick, thank you!
