### ISSUE TITLE
How to import the module

### ISSUE THREAD

**Issue by jeantristan** [komoot/staticmap#2]
I installed the module but I'm not able to use it.
Coud you help me please ?

```
In [1]: import staticmap

In [2]: staticmap.StaticMap(300,400,10)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-f766ae52cee2> in <module>()
----> 1 staticmap.StaticMap(300,400,10)

AttributeError: 'module' object has no attribute 'StaticMap'

```

**Comment by christophlingg** [comment]
it's

```
staticmap.staticmap.StaticMap()
```

which is not very elegant I admit. I saw that [popular packages](https://github.com/kennethreitz/requests/blob/master/requests/__init__.py#L66) introduce shortcuts which are very handy. I'll add them too. Your code should work as as well in the future.

**Comment by christophlingg** [comment]
the current version of staticmap 0.4.7 supports those shortcuts
