### ISSUE TITLE
Custom Tile Server

### ISSUE THREAD

**Issue by maxwell-oroark** [komoot/staticmap#21]
If we are fetching tiles from a server that requires we pass a `Bearer {token}` is there a way to pass this to the library so it can correctly supply it in the request?

**Comment by yterletskyi** [comment]
It looks like it is. `StaticMap` takes headers parameter in constructor.
See https://github.com/komoot/staticmap/blob/master/staticmap/staticmap.py#L212

**Comment by christophlingg** [comment]
exactly, that is explained in the readme: https://github.com/komoot/staticmap#create-a-new-map-instance
